<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findCount()
    {
//        $qb = $this->createQueryBuilder('c');
//        $qb 
//           ->groupBy('c.posts')
//        ;
                       
        
        
        
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('c')
                ->addSelect('COUNT(p)')
                ->from('AppBundle:Category', 'c')
                ->leftJoin('AppBundle:Post', 'p')
                ->groupBy('c.id');
        return $qb->getQuery()->getResult();
    }
}
