<?php
namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use Doctrine\ORM\EntityRepository;


/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
     public function findAllByPost(Post $post)
    {
        $qb = $this->createQueryBuilder('c');
        $qb
           ->where('IDENTITY(c.post) = '.$post->getId())
           ->orderBy('c.date', 'DESC')
        ;
        
        return $qb->getQuery()->getResult();
    }
    
    public function findLatestByPost(Post $post, $limit)
    {
        $qb = $this->createQueryBuilder('d');
        $qb 
           ->where('IDENTITY(d.post) = '.$post->getId())
           ->orderBy('d.id', 'DESC')
           ->setMaxResults($limit) // pour créer la limite
        ;
                       
        return $qb->getQuery()->getResult();
    }
}
