<?php

namespace AppBundle\Repository;

/**
 * GamesFinishedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesFinishedRepository extends \Doctrine\ORM\EntityRepository
{

}
