<?php

namespace AppBundle\Repository;

/**
 * GameModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameModeRepository extends \Doctrine\ORM\EntityRepository
{
}
