<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findLatest($limit)
    {
        $qb = $this->createQueryBuilder('a');
        $qb 
           ->orderBy('a.id', 'DESC')
           ->setMaxResults($limit) // pour créer la limite
        ;
                       
        return $qb->getQuery()->getResult();
    }
//    
//    public function findByCategory($category)
//    {
//        $query = $this->createQueryBuilder('p')
//                      ->select('p')
//                      ->leftJoin('p.categories', 'c')
//                      ->addSelect('c');
// 
//        $query = $query->add('where', $query->expr()->in('c', ':c'))
//                      ->setParameter('c', $category)
//                      ->getQuery()
//                      ->getResult();
//          
//        return $query;
//    }
    
    public function findByCategory($category)
    {
        $query = $this->createQueryBuilder('p')
                      ->leftJoin('p.categories', 'c')
                      ->where('c.id = :c')
                      ->setParameter('c', $category)
                      ->getQuery()
                      ->getResult();
          
        return $query;
    }
    
//    public function findByAuthor($id)
//    {
//        $qb = $this->createQueryBuilder('p');
//        $qb
//           ->where('IDENTITY(p.author) = :id')
////           ->setMaxResults($limit)
//           ->orderBy('p.id', 'DESC')
//           ->setParameter('id', $id)
//        ;
//    }
}
