<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest($limit)
    {
        $qb = $this->createQueryBuilder('a');
        $qb 
           ->orderBy('a.id', 'DESC')
           ->setMaxResults($limit) // pour créer la limite
        ;
                       
        return $qb->getQuery()->getResult();
    }
}
