<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRepository extends EntityRepository
{
    public function findDistinctRanking(){
        $qb = $this->createQueryBuilder('r')
                   ->groupBy('r.competition_id')
                ;
        return $qb->getQuery()->getResult();
    }
}
