<?php

namespace AppBundle\Repository;

/**
 * RankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingRepository extends \Doctrine\ORM\EntityRepository
{
}
