<?php

namespace AppBundle\Repository;

/**
 * TypeOfGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeOfGameRepository extends \Doctrine\ORM\EntityRepository
{
}
